<LoginScreen>
    MDCard:
        size_hint: None, None
        size: 800, 700
        pos_hint: {'center_x':.5, 'center_y':.5}
        elevation: 10
        padding: 20, 20, 20, 20
        spacing: 20
        orientation: "vertical"

        MDLabel:
            text: "Anmeldung"
            font_size: "35sp"
            halign: "center"
            size_hint: 1, None
            height: self.texture_size[1]
            padding_y: 10

        MDTextField:
            id: username
            hint_text: "Username"
            icon_right: "account"
            size_hint: 0.8, None
            width: 600
            font_size: "15sp"
            pos_hint: {'center_x':.5}

        MDTextField:
            id: password
            hint_text: "Password"
            icon_right: "lock"
            size_hint: 0.8, None
            width: 600
            font_size: "15sp"
            pos_hint: {'center_x':.5}
            password: True

        MDRoundFlatButton:
            text: "Login"
            font_size: "15sp"
            size_hint: 0.8, None
            width: 400
            pos_hint: {'center_x':.5}
            on_press: root.validate_user()

        MDLabel
            id: error_label
            text: "Please Login"
            font_size: "15sp"
            valign: "top"
            halign: "center"
            size_hint: 0.8, None
            height: self.texture_size[1]
            pos_hint: {'center_x':.5}

<CreateTeamScreen>
    MDBoxLayout:
        id: layout_create_team
        orientation: "vertical"
        size_hint: 0.8, 0.8
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        spacing: 10
        MDScrollView:
            do_scroll_x: False
            MDGridLayout:
                id: layout_clowns_select
                cols: 1
                size_hint: 1, 1
                padding: 0, 10, 0, 10
                spacing: 10
                row_force_default: True
                row_default_height: 50
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        MDDropDownItem:
            id: dropdown_locations
            text: "Select Location"
            # font_size: "36sp"
            font_style: "H5"
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.open_location_menu(self)
        Widget:
            size_hint: 1, None
            height: 10
        MDRoundFlatButton:
            text: "Create Team"
            # font_size: "36sp"
            font_style: "H6"
            size_hint: 0.8, None
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_press: root.create_team()


<ChatScreen>
    GridLayout:
        cols: 1
        size_hint: 1, 1
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        GridLayout:
            cols: 2
            padding: 20, 20, 20, 0
            spacing: 10
            size_hint: 1, None
            height: '48dp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            MDRoundFlatButton:
                text: 'Open Chat'
                font_size: 36
                size_hint: 0.5, None
                height: '48dp'
                on_release: root.create_connection_service()
            MDRoundFlatButton:
                text: 'Logout'
                font_size: 36
                size_hint: 0.5, None
                height: '48dp'
                on_release: root.ask_for_logout()
        MDTabs:
            id: chat_tabs
            anchor_y: "bottom"
            on_tab_switch: root.on_tab_switch(*args)


<ChatTab>
    GridLayout:
        cols: 1
        size_hint: 1, 1
        pos_hint: {'center_x': 0.5, 'top': 1}
        MDScrollView:
            do_scroll_x: False
            do_scroll_y: True
            size_hint: 1, 1

            BoxLayout:
                id: output
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

                # Beispiel für eine eingehende Nachricht
                MDLabel:
                    text: 'Eingehende Nachricht'
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    valign: 'middle'
                    padding: 10
                    canvas.before:
                        Color:
                            rgba: (1, 0, 0, 0.3)  # Rot für eingehende Nachrichten
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]

                # Beispiel für eine ausgehende Nachricht
                MDLabel:
                    text: 'Ausgehende Nachricht'
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'right'
                    valign: 'middle'
                    padding: 10
                    canvas.before:
                        Color:
                            rgba: (0, 0, 1, 0.3)  # Blau für ausgehende Nachrichten
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [10]
        GridLayout:
            cols: 2
            size_hint: 1, None
            MDTextField:
                id: input
                font_size: 36
                padding: 20, 0, 0, 0
                font_name: 'fonts/seguiemj'
                multiline: False
                hint_text: 'Type your message here'
                input_type: 'text'
                keyboard_suggestions: True
                height: '48dp'
            MDIconButton:
                icon: 'send'
                # size_hint: 1, None
                height: '48dp'
                on_release: root.send_message()
        Widget:
            size_hint: 1, None
            height: '72dp'


<MessageLabel@MDLabel>:
    size_hint_y: None
    height: self.texture_size[1]
    valign: 'middle'
    padding: 10
    canvas.before:
        Color:
            rgba: root.color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10]
